### ISSUE TITLE
Improve the exercise

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m1-evaluacion-intermedia-irenegf83#1]
Awesome job @irenegf83  !!!

Here you have some tips to improve the exercise:

- [x] Fix the meta title of the page
- [x] We need an h1 tag
- [x] Finish the main title styles: words should jump.
- [x] You have used `position: fixed;` on header add `top` and `left` also.

Let me know if you have any doubts ;)

Go for it!!

**Comment by irene-gomez** [comment]
@nasivuela the issues are fixed

**Comment by nasivuela** [comment]
Cool, you got it!

![](https://media.giphy.com/media/wue4QtxncWuE8/giphy.gif)

Just a little detail, check the meta title something like --> 'Adalab Digital'  would be better ;)
